/* File generated by: simse.codegenerator.explanatorytoolgenerator.ActionInfoWindowGenerator */
package simse.explanatorytool;

import javax.swing.*;

import java.awt.Dimension;
import java.awt.event.WindowAdapter;
import java.awt.event.WindowEvent;

public class ActionInfoWindow extends JFrame {

	public ActionInfoWindow(JFrame owner, String actionName,
			simse.adts.actions.Action action, int clockTick) {
		super(actionName + " Info for Clock Tick " + clockTick);
		// Create main panel:
		JTabbedPane mainPane = new JTabbedPane();
		mainPane.setPreferredSize(new Dimension(900, 550));

		// add action info panel:
		ActionInfoPanel actionPanel = new ActionInfoPanel(action);
		mainPane.addTab("Action Info", actionPanel);

		// add rule info panel:
		RuleInfoPanel rulePanel = new RuleInfoPanel(this, action);
		mainPane.addTab("Rule Info", rulePanel);

		// Set main window frame properties:
		mainPane.setOpaque(true);
		addWindowListener(new ExitListener());
		setContentPane(mainPane);
		setVisible(true);
		setSize(getLayout().preferredLayoutSize(this));

		// Make it show up in the center of the screen:
		setLocationRelativeTo(null);
		validate();
		pack();
		repaint();
	}

	public class ExitListener extends WindowAdapter {
		public void windowClosing(WindowEvent event) {
			setVisible(false);
			dispose();
		}
	}
}