/* File generated by: simse.codegenerator.stategenerator.ADTGenerator */
package simse.adts.actions;

import simse.adts.objects.SSObject;
import simse.util.IDGenerator;

import java.util.*;

public abstract class Action implements Cloneable {
	private int id;
	private int timeElapsed;

	public Action() {
		id = IDGenerator.getNextID();
		timeElapsed = 0;
	}

	public Object clone() {
		try {
			Action cl = (Action) (super.clone());
			cl.id = id;
			cl.timeElapsed = timeElapsed;
			return cl;
		} catch (CloneNotSupportedException c) {
			System.out.println(c.getMessage());
		}
		return null;
	}

	public int getId() {
		return id;
	}

	public void incrementTimeElapsed() {
		timeElapsed++;
	}

	public int getTimeElapsed() {
		return timeElapsed;
	}

	public abstract Vector<SSObject> getAllParticipants();

	public abstract Vector<SSObject> getAllActiveParticipants();

	public abstract Vector<SSObject> getAllInactiveParticipants();
}