/* File generated by: simse.codegenerator.stategenerator.RepositoryGenerator */
package simse.state;

import simse.adts.objects.*;
import java.util.*;

public class CustomerStateRepository implements Cloneable {
	ACustomerStateRepository a0;

	public CustomerStateRepository() {
		a0 = new ACustomerStateRepository();
	}

	public Object clone() {
		try {
			CustomerStateRepository cl = (CustomerStateRepository) (super
					.clone());
			cl.a0 = (ACustomerStateRepository) (a0.clone());
			return cl;
		} catch (CloneNotSupportedException c) {
			System.out.println(c.getMessage());
		}
		return null;
	}

	public Vector<Customer> getAll() {
		Vector<Customer> all = new Vector<Customer>();
		all.addAll(a0.getAll());
		return all;
	}

	public ACustomerStateRepository getACustomerStateRepository() {
		return a0;
	}
}