/* File generated by: simse.codegenerator.stategenerator.RepositoryGenerator */
package simse.state;

import simse.adts.objects.*;
import java.util.*;

public class ProjectStateRepository implements Cloneable {
	SEProjectStateRepository s0;

	public ProjectStateRepository() {
		s0 = new SEProjectStateRepository();
	}

	public Object clone() {
		try {
			ProjectStateRepository cl = (ProjectStateRepository) (super.clone());
			cl.s0 = (SEProjectStateRepository) (s0.clone());
			return cl;
		} catch (CloneNotSupportedException c) {
			System.out.println(c.getMessage());
		}
		return null;
	}

	public Vector<Project> getAll() {
		Vector<Project> all = new Vector<Project>();
		all.addAll(s0.getAll());
		return all;
	}

	public SEProjectStateRepository getSEProjectStateRepository() {
		return s0;
	}
}