/* File generated by: simse.codegenerator.logicgenerator.dialoggenerator.NonEmployeeParticipantSelectionDialogGenerator */
package simse.logic.dialogs;

import simse.gui.ImageLoader;
import simse.gui.TabPanel;
import simse.state.*;
import simse.adts.objects.*;
import simse.adts.actions.*;
import java.util.*;
import javax.swing.*;
import java.awt.event.*;
import java.awt.*;
import javax.swing.border.*;
import javax.swing.event.*;

public class NonEmployeeParticipantSelectionDialog extends JDialog implements
		ActionListener {
	private String partName;
	private Vector<SSObject> participants;
	private simse.adts.actions.Action action;
	private State state;
	private int minNumParts;
	private int maxNumParts;
	private Vector<JCheckBox> checkBoxes;
	private JButton checkAllButton;
	private JButton clearAllButton;
	private JButton okButton;
	private JButton cancelButton;
	private boolean actionCancelled;

	public NonEmployeeParticipantSelectionDialog(JFrame owner, String pName,
			Vector<SSObject> parts, simse.adts.actions.Action act, State s) {
		super(owner, true);
		partName = pName;
		participants = parts;
		action = act;
		state = s;
		actionCancelled = false;
		setMinAndMax();
		if ((minNumParts == 0) || (participants.size() > 1)) {
			checkBoxes = new Vector<JCheckBox>();
			setTitle("Participant Selection");
			Box mainPane = Box.createVerticalBox();
			JPanel topPane = new JPanel();
			String title = "Choose ";
			title = title.concat(partName + " participant(s) (");
			if (minNumParts == maxNumParts) {
				title = title.concat("exactly " + minNumParts);
			} else {
				title = title.concat("at least " + minNumParts);
				if (maxNumParts < 999999) // not boundless
				{
					title = title.concat(", at most " + maxNumParts);
				}
			}
			title = title.concat("):");
			topPane.add(new JLabel(title));
			JPanel middlePane = new JPanel(new GridLayout(0, 1));
			for (int i = 0; i < participants.size(); i++) {
				SSObject tempObj = participants.elementAt(i);
				String label = new String();
				if (tempObj instanceof SoftwareEngineer) {
					label = ("SoftwareEngineer ("
							+ ((SoftwareEngineer) tempObj).getName() + ")");
				} else if (tempObj instanceof RequirementsDocument) {
					label = ("RequirementsDocument ("
							+ ((RequirementsDocument) tempObj).getName() + ")");
				} else if (tempObj instanceof DesignDocument) {
					label = ("DesignDocument ("
							+ ((DesignDocument) tempObj).getName() + ")");
				} else if (tempObj instanceof Code) {
					label = ("Code (" + ((Code) tempObj).getName() + ")");
				} else if (tempObj instanceof SystemTestPlan) {
					label = ("SystemTestPlan ("
							+ ((SystemTestPlan) tempObj).getName() + ")");
				} else if (tempObj instanceof SEProject) {
					label = ("SEProject ("
							+ ((SEProject) tempObj).getDescription() + ")");
				} else if (tempObj instanceof RequirementsCaptureTool) {
					label = ("RequirementsCaptureTool ("
							+ ((RequirementsCaptureTool) tempObj).getName() + ")");
				} else if (tempObj instanceof DesignEnvironment) {
					label = ("DesignEnvironment ("
							+ ((DesignEnvironment) tempObj).getName() + ")");
				} else if (tempObj instanceof IDE) {
					label = ("IDE (" + ((IDE) tempObj).getName() + ")");
				} else if (tempObj instanceof AutomatedTestingTool) {
					label = ("AutomatedTestingTool ("
							+ ((AutomatedTestingTool) tempObj).getName() + ")");
				} else if (tempObj instanceof ACustomer) {
					label = ("ACustomer (" + ((ACustomer) tempObj).getName() + ")");
				}
				JPanel tempPane = new JPanel(new BorderLayout());
				JCheckBox tempCheckBox = new JCheckBox(label);
				tempPane.add(tempCheckBox, BorderLayout.WEST);
				checkBoxes.add(tempCheckBox);
				ImageIcon icon = new ImageIcon(ImageLoader.getImageFromURL(
						TabPanel.getImage(tempObj)).getScaledInstance(30, 30,
						Image.SCALE_AREA_AVERAGING));
				tempPane.add(new JLabel(icon), BorderLayout.EAST);
				middlePane.add(tempPane);
			}
			JPanel checkPane = new JPanel();
			checkAllButton = new JButton("Check All");
			checkAllButton.addActionListener(this);
			checkPane.add(checkAllButton);
			clearAllButton = new JButton("Clear All");
			clearAllButton.addActionListener(this);
			checkPane.add(clearAllButton);
			JPanel bottomPane = new JPanel();
			okButton = new JButton("OK");
			okButton.addActionListener(this);
			bottomPane.add(okButton);
			cancelButton = new JButton("Cancel");
			cancelButton.addActionListener(this);
			bottomPane.add(cancelButton);
			mainPane.add(topPane);
			mainPane.add(middlePane);
			JSeparator separator1 = new JSeparator();
			separator1.setMaximumSize(new Dimension(900, 1));
			mainPane.add(separator1);
			mainPane.add(checkPane);
			JSeparator separator2 = new JSeparator();
			separator2.setMaximumSize(new Dimension(900, 1));
			mainPane.add(separator2);
			mainPane.add(bottomPane);
			addWindowListener(new ExitListener());
			setContentPane(mainPane);
			validate();
			pack();
			repaint();
			toFront();
			Point ownerLoc = owner.getLocationOnScreen();
			Point thisLoc = new Point();
			thisLoc.setLocation(
					(ownerLoc.getX() + (owner.getWidth() / 2) - (this
							.getWidth() / 2)),
					(ownerLoc.getY() + (owner.getHeight() / 2) - (this
							.getHeight() / 2)));
			setLocation(thisLoc);
			setVisible(true);
		} else {
			if (action instanceof CreateRequirementsAction) {
				if (partName.equals("ReqDoc")) {
					((CreateRequirementsAction) action)
							.addReqDoc((Artifact) participants.elementAt(0));
				} else if (partName.equals("Proj")) {
					((CreateRequirementsAction) action)
							.addProj((Project) participants.elementAt(0));
				} else if (partName.equals("RequirementsCaptureTool")) {
					((CreateRequirementsAction) action)
							.addRequirementsCaptureTool((Tool) participants
									.elementAt(0));
				} else if (partName.equals("AssociatedCodeDoc")) {
					((CreateRequirementsAction) action)
							.addAssociatedCodeDoc((Artifact) participants
									.elementAt(0));
				} else if (partName.equals("AssociatedDesignDoc")) {
					((CreateRequirementsAction) action)
							.addAssociatedDesignDoc((Artifact) participants
									.elementAt(0));
				} else if (partName.equals("AssociatedSystemTestPlan")) {
					((CreateRequirementsAction) action)
							.addAssociatedSystemTestPlan((Artifact) participants
									.elementAt(0));
				}
			} else if (action instanceof ReviewRequirementsAction) {
				if (partName.equals("RequirementsDoc")) {
					((ReviewRequirementsAction) action)
							.addRequirementsDoc((Artifact) participants
									.elementAt(0));
				} else if (partName.equals("Proj")) {
					((ReviewRequirementsAction) action)
							.addProj((Project) participants.elementAt(0));
				}
			} else if (action instanceof CorrectRequirementsAction) {
				if (partName.equals("RequirementsDoc")) {
					((CorrectRequirementsAction) action)
							.addRequirementsDoc((Artifact) participants
									.elementAt(0));
				} else if (partName.equals("Proj")) {
					((CorrectRequirementsAction) action)
							.addProj((Project) participants.elementAt(0));
				} else if (partName.equals("RequirementsCaptureTool")) {
					((CorrectRequirementsAction) action)
							.addRequirementsCaptureTool((Tool) participants
									.elementAt(0));
				}
			} else if (action instanceof CreateDesignAction) {
				if (partName.equals("DesignDoc")) {
					((CreateDesignAction) action)
							.addDesignDoc((Artifact) participants.elementAt(0));
				} else if (partName.equals("Proj")) {
					((CreateDesignAction) action)
							.addProj((Project) participants.elementAt(0));
				} else if (partName.equals("AssociatedRequirementsDoc")) {
					((CreateDesignAction) action)
							.addAssociatedRequirementsDoc((Artifact) participants
									.elementAt(0));
				} else if (partName.equals("DesignEnvironment")) {
					((CreateDesignAction) action)
							.addDesignEnvironment((Tool) participants
									.elementAt(0));
				} else if (partName.equals("AssociatedCodeDoc")) {
					((CreateDesignAction) action)
							.addAssociatedCodeDoc((Artifact) participants
									.elementAt(0));
				}
			} else if (action instanceof ReviewDesignAction) {
				if (partName.equals("DesignDoc")) {
					((ReviewDesignAction) action)
							.addDesignDoc((Artifact) participants.elementAt(0));
				} else if (partName.equals("Proj")) {
					((ReviewDesignAction) action)
							.addProj((Project) participants.elementAt(0));
				} else if (partName.equals("AssociatedRequirementsDoc")) {
					((ReviewDesignAction) action)
							.addAssociatedRequirementsDoc((Artifact) participants
									.elementAt(0));
				}
			} else if (action instanceof CorrectDesignAction) {
				if (partName.equals("DesignDoc")) {
					((CorrectDesignAction) action)
							.addDesignDoc((Artifact) participants.elementAt(0));
				} else if (partName.equals("Proj")) {
					((CorrectDesignAction) action)
							.addProj((Project) participants.elementAt(0));
				} else if (partName.equals("AssociatedRequirementsDoc")) {
					((CorrectDesignAction) action)
							.addAssociatedRequirementsDoc((Artifact) participants
									.elementAt(0));
				} else if (partName.equals("DesignEnvironment")) {
					((CorrectDesignAction) action)
							.addDesignEnvironment((Tool) participants
									.elementAt(0));
				}
			} else if (action instanceof CreateCodeAction) {
				if (partName.equals("CodeDoc")) {
					((CreateCodeAction) action)
							.addCodeDoc((Artifact) participants.elementAt(0));
				} else if (partName.equals("Proj")) {
					((CreateCodeAction) action).addProj((Project) participants
							.elementAt(0));
				} else if (partName.equals("AssociatedRequirementsDoc")) {
					((CreateCodeAction) action)
							.addAssociatedRequirementsDoc((Artifact) participants
									.elementAt(0));
				} else if (partName.equals("AssociatedDesignDocument")) {
					((CreateCodeAction) action)
							.addAssociatedDesignDocument((Artifact) participants
									.elementAt(0));
				} else if (partName.equals("DevelopmentEnvironment")) {
					((CreateCodeAction) action)
							.addDevelopmentEnvironment((Tool) participants
									.elementAt(0));
				} else if (partName.equals("AssociatedSystemTestPlan")) {
					((CreateCodeAction) action)
							.addAssociatedSystemTestPlan((Artifact) participants
									.elementAt(0));
				}
			} else if (action instanceof InspectCodeAction) {
				if (partName.equals("CodeDoc")) {
					((InspectCodeAction) action)
							.addCodeDoc((Artifact) participants.elementAt(0));
				} else if (partName.equals("Proj")) {
					((InspectCodeAction) action).addProj((Project) participants
							.elementAt(0));
				} else if (partName.equals("AssociatedRequirementsDoc")) {
					((InspectCodeAction) action)
							.addAssociatedRequirementsDoc((Artifact) participants
									.elementAt(0));
				} else if (partName.equals("AssociatedDesignDoc")) {
					((InspectCodeAction) action)
							.addAssociatedDesignDoc((Artifact) participants
									.elementAt(0));
				}
			} else if (action instanceof CorrectCodeAction) {
				if (partName.equals("CodeDoc")) {
					((CorrectCodeAction) action)
							.addCodeDoc((Artifact) participants.elementAt(0));
				} else if (partName.equals("Proj")) {
					((CorrectCodeAction) action).addProj((Project) participants
							.elementAt(0));
				} else if (partName.equals("AssociatedRequirementsDoc")) {
					((CorrectCodeAction) action)
							.addAssociatedRequirementsDoc((Artifact) participants
									.elementAt(0));
				} else if (partName.equals("AssociatedDesignDoc")) {
					((CorrectCodeAction) action)
							.addAssociatedDesignDoc((Artifact) participants
									.elementAt(0));
				} else if (partName.equals("DevelopmentEnvironment")) {
					((CorrectCodeAction) action)
							.addDevelopmentEnvironment((Tool) participants
									.elementAt(0));
				}
			} else if (action instanceof IntegrateCodeAction) {
				if (partName.equals("CodeDoc")) {
					((IntegrateCodeAction) action)
							.addCodeDoc((Artifact) participants.elementAt(0));
				} else if (partName.equals("Proj")) {
					((IntegrateCodeAction) action)
							.addProj((Project) participants.elementAt(0));
				} else if (partName.equals("AssociatedRequirementsDoc")) {
					((IntegrateCodeAction) action)
							.addAssociatedRequirementsDoc((Artifact) participants
									.elementAt(0));
				} else if (partName.equals("AssociatedDesignDoc")) {
					((IntegrateCodeAction) action)
							.addAssociatedDesignDoc((Artifact) participants
									.elementAt(0));
				} else if (partName.equals("DevelopmentEnvironment")) {
					((IntegrateCodeAction) action)
							.addDevelopmentEnvironment((Tool) participants
									.elementAt(0));
				}
			} else if (action instanceof SystemTestAction) {
				if (partName.equals("CodeDoc")) {
					((SystemTestAction) action)
							.addCodeDoc((Artifact) participants.elementAt(0));
				} else if (partName.equals("Proj")) {
					((SystemTestAction) action).addProj((Project) participants
							.elementAt(0));
				} else if (partName.equals("AssociatedSystemTestPlan")) {
					((SystemTestAction) action)
							.addAssociatedSystemTestPlan((Artifact) participants
									.elementAt(0));
				} else if (partName.equals("TestingTool")) {
					((SystemTestAction) action)
							.addTestingTool((Tool) participants.elementAt(0));
				}
			} else if (action instanceof CreateSystemTestPlanAction) {
				if (partName.equals("AssociatedCodeDoc")) {
					((CreateSystemTestPlanAction) action)
							.addAssociatedCodeDoc((Artifact) participants
									.elementAt(0));
				} else if (partName.equals("Proj")) {
					((CreateSystemTestPlanAction) action)
							.addProj((Project) participants.elementAt(0));
				} else if (partName.equals("SystemTestPlanDoc")) {
					((CreateSystemTestPlanAction) action)
							.addSystemTestPlanDoc((Artifact) participants
									.elementAt(0));
				} else if (partName.equals("AssociatedRequirementsDoc")) {
					((CreateSystemTestPlanAction) action)
							.addAssociatedRequirementsDoc((Artifact) participants
									.elementAt(0));
				} else if (partName.equals("TestingTool")) {
					((CreateSystemTestPlanAction) action)
							.addTestingTool((Tool) participants.elementAt(0));
				}
			} else if (action instanceof ReviewSystemTestPlanAction) {
				if (partName.equals("TestPlan")) {
					((ReviewSystemTestPlanAction) action)
							.addTestPlan((Artifact) participants.elementAt(0));
				} else if (partName.equals("AssociatedRequirementsDoc")) {
					((ReviewSystemTestPlanAction) action)
							.addAssociatedRequirementsDoc((Artifact) participants
									.elementAt(0));
				} else if (partName.equals("Proj")) {
					((ReviewSystemTestPlanAction) action)
							.addProj((Project) participants.elementAt(0));
				}
			} else if (action instanceof CorrectSystemTestPlanAction) {
				if (partName.equals("TestPlan")) {
					((CorrectSystemTestPlanAction) action)
							.addTestPlan((Artifact) participants.elementAt(0));
				} else if (partName.equals("AssociatedRequirementsDoc")) {
					((CorrectSystemTestPlanAction) action)
							.addAssociatedRequirementsDoc((Artifact) participants
									.elementAt(0));
				} else if (partName.equals("Proj")) {
					((CorrectSystemTestPlanAction) action)
							.addProj((Project) participants.elementAt(0));
				} else if (partName.equals("TestingTool")) {
					((CorrectSystemTestPlanAction) action)
							.addTestingTool((Tool) participants.elementAt(0));
				}
			} else if (action instanceof DeliverProductAction) {
				if (partName.equals("Proj")) {
					((DeliverProductAction) action)
							.addProj((Project) participants.elementAt(0));
				} else if (partName.equals("CodeDoc")) {
					((DeliverProductAction) action)
							.addCodeDoc((Artifact) participants.elementAt(0));
				} else if (partName.equals("Cust")) {
					((DeliverProductAction) action)
							.addCust((Customer) participants.elementAt(0));
				}
			} else if (action instanceof BreakAction) {
			} else if (action instanceof GetSickAction) {
			} else if (action instanceof QuitAction) {
			} else if (action instanceof IntroduceNewRequirementsAction) {
				if (partName.equals("Cust")) {
					((IntroduceNewRequirementsAction) action)
							.addCust((Customer) participants.elementAt(0));
				} else if (partName.equals("AssociatedRequirementsDocument")) {
					((IntroduceNewRequirementsAction) action)
							.addAssociatedRequirementsDocument((Artifact) participants
									.elementAt(0));
				} else if (partName.equals("Proj")) {
					((IntroduceNewRequirementsAction) action)
							.addProj((Project) participants.elementAt(0));
				} else if (partName.equals("AssociatedCode")) {
					((IntroduceNewRequirementsAction) action)
							.addAssociatedCode((Artifact) participants
									.elementAt(0));
				} else if (partName.equals("AssociatedDesignDocument")) {
					((IntroduceNewRequirementsAction) action)
							.addAssociatedDesignDocument((Artifact) participants
									.elementAt(0));
				} else if (partName.equals("AssociatedSystemTestPlan")) {
					((IntroduceNewRequirementsAction) action)
							.addAssociatedSystemTestPlan((Artifact) participants
									.elementAt(0));
				}
			} else if (action instanceof UpdateProjectAttributesAction) {
				if (partName.equals("Proj")) {
					((UpdateProjectAttributesAction) action)
							.addProj((Project) participants.elementAt(0));
				}
			} else if (action instanceof ChangePayRateAction) {
			} else if (action instanceof GiveBonusAction) {
				if (partName.equals("ProjectWithBudget")) {
					((GiveBonusAction) action)
							.addProjectWithBudget((Project) participants
									.elementAt(0));
				}
			} else if (action instanceof FireAction) {
			} else if (action instanceof PurchaseToolAction) {
				if (partName.equals("SETool")) {
					((PurchaseToolAction) action).addSETool((Tool) participants
							.elementAt(0));
				} else if (partName.equals("Proj")) {
					((PurchaseToolAction) action)
							.addProj((Project) participants.elementAt(0));
				}
			} else if (action instanceof SuggestedRequirementsPhaseDurationAction) {
				if (partName.equals("Proj")) {
					((SuggestedRequirementsPhaseDurationAction) action)
							.addProj((Project) participants.elementAt(0));
				}
			} else if (action instanceof SuggestedDesignPhaseDurationAction) {
				if (partName.equals("Proj")) {
					((SuggestedDesignPhaseDurationAction) action)
							.addProj((Project) participants.elementAt(0));
				}
			} else if (action instanceof SuggestedImplIntegrationPhaseDurationAction) {
				if (partName.equals("Proj")) {
					((SuggestedImplIntegrationPhaseDurationAction) action)
							.addProj((Project) participants.elementAt(0));
				}
			} else if (action instanceof SuggestedTestingPhaseDurationAction) {
				if (partName.equals("Proj")) {
					((SuggestedTestingPhaseDurationAction) action)
							.addProj((Project) participants.elementAt(0));
				}
			}
		}
	}

	public void actionPerformed(ActionEvent evt) {
		Object source = evt.getSource();
		if (source == cancelButton) {
			actionCancelled = true;
			setVisible(false);
			dispose();
		} else if (source == okButton) {
			Vector<JCheckBox> checkedBoxes = new Vector<JCheckBox>();
			for (int i = 0; i < checkBoxes.size(); i++) {
				JCheckBox tempCBox = checkBoxes.elementAt(i);
				if (tempCBox.isSelected()) {
					checkedBoxes.add(tempCBox);
				}
			}
			if (checkedBoxes.size() < minNumParts) {
				JOptionPane
						.showMessageDialog(null, ("You must choose at least "
								+ minNumParts + " participants"),
								"Invalid Input", JOptionPane.ERROR_MESSAGE);
			} else if (checkedBoxes.size() > maxNumParts) {
				JOptionPane
						.showMessageDialog(
								null,
								("You may only choose at most " + maxNumParts + " participants"),
								"Invalid Input", JOptionPane.ERROR_MESSAGE);
			} else {
				for (int i = 0; i < checkedBoxes.size(); i++) {
					JCheckBox checkedBox = checkedBoxes.elementAt(i);
					String cBoxText = checkedBox.getText();
					String objTypeName = cBoxText.substring(0,
							(cBoxText.indexOf('(') - 1));
					String keyValStr = cBoxText.substring(
							(cBoxText.indexOf('(') + 1),
							cBoxText.lastIndexOf(')'));

					addParticipant(objTypeName, keyValStr);
				}
				setVisible(false);
				dispose();
			}
		} else if (source == checkAllButton) {
			for (int i = 0; i < checkBoxes.size(); i++) {
				checkBoxes.elementAt(i).setSelected(true);
			}
		} else if (source == clearAllButton) {
			for (int i = 0; i < checkBoxes.size(); i++) {
				checkBoxes.elementAt(i).setSelected(false);
			}
		}
	}

	private void addParticipant(String objTypeName, String keyValStr) {
		if (objTypeName.equals("SoftwareEngineer")) {
			SoftwareEngineer a = state.getEmployeeStateRepository()
					.getSoftwareEngineerStateRepository().get(keyValStr);
			if (a != null) {
				if (action instanceof CreateRequirementsAction) {
					if (partName.equals("Emp")) {
						((CreateRequirementsAction) action)
								.addEmp((Employee) a);
					}
				} else if (action instanceof ReviewRequirementsAction) {
					if (partName.equals("Emp")) {
						((ReviewRequirementsAction) action)
								.addEmp((Employee) a);
					}
				} else if (action instanceof CorrectRequirementsAction) {
					if (partName.equals("Emp")) {
						((CorrectRequirementsAction) action)
								.addEmp((Employee) a);
					}
				} else if (action instanceof CreateDesignAction) {
					if (partName.equals("Emp")) {
						((CreateDesignAction) action).addEmp((Employee) a);
					}
				} else if (action instanceof ReviewDesignAction) {
					if (partName.equals("Emp")) {
						((ReviewDesignAction) action).addEmp((Employee) a);
					}
				} else if (action instanceof CorrectDesignAction) {
					if (partName.equals("Emp")) {
						((CorrectDesignAction) action).addEmp((Employee) a);
					}
				} else if (action instanceof CreateCodeAction) {
					if (partName.equals("Emp")) {
						((CreateCodeAction) action).addEmp((Employee) a);
					}
				} else if (action instanceof InspectCodeAction) {
					if (partName.equals("Emp")) {
						((InspectCodeAction) action).addEmp((Employee) a);
					}
				} else if (action instanceof CorrectCodeAction) {
					if (partName.equals("Emp")) {
						((CorrectCodeAction) action).addEmp((Employee) a);
					}
				} else if (action instanceof IntegrateCodeAction) {
					if (partName.equals("Emp")) {
						((IntegrateCodeAction) action).addEmp((Employee) a);
					}
				} else if (action instanceof SystemTestAction) {
					if (partName.equals("Emp")) {
						((SystemTestAction) action).addEmp((Employee) a);
					}
				} else if (action instanceof CreateSystemTestPlanAction) {
					if (partName.equals("Emp")) {
						((CreateSystemTestPlanAction) action)
								.addEmp((Employee) a);
					}
				} else if (action instanceof ReviewSystemTestPlanAction) {
					if (partName.equals("Emp")) {
						((ReviewSystemTestPlanAction) action)
								.addEmp((Employee) a);
					}
				} else if (action instanceof CorrectSystemTestPlanAction) {
					if (partName.equals("Emp")) {
						((CorrectSystemTestPlanAction) action)
								.addEmp((Employee) a);
					}
				} else if (action instanceof DeliverProductAction) {
					if (partName.equals("Emp")) {
						((DeliverProductAction) action).addEmp((Employee) a);
					}
				} else if (action instanceof ChangePayRateAction) {
					if (partName.equals("Emp")) {
						((ChangePayRateAction) action).addEmp((Employee) a);
					}
				} else if (action instanceof GiveBonusAction) {
					if (partName.equals("Emp")) {
						((GiveBonusAction) action).addEmp((Employee) a);
					}
				} else if (action instanceof FireAction) {
					if (partName.equals("FiredPerson")) {
						((FireAction) action).addFiredPerson((Employee) a);
					}
				} else if (action instanceof PurchaseToolAction) {
					if (partName.equals("EmpWhoseMenuClickedOn")) {
						((PurchaseToolAction) action)
								.addEmpWhoseMenuClickedOn((Employee) a);
					}
				}
			}
		} else if (objTypeName.equals("RequirementsDocument")) {
			RequirementsDocument a = state.getArtifactStateRepository()
					.getRequirementsDocumentStateRepository().get(keyValStr);
			if (a != null) {
				if (action instanceof CreateRequirementsAction) {
					if (partName.equals("ReqDoc")) {
						((CreateRequirementsAction) action)
								.addReqDoc((Artifact) a);
					}
				} else if (action instanceof ReviewRequirementsAction) {
					if (partName.equals("RequirementsDoc")) {
						((ReviewRequirementsAction) action)
								.addRequirementsDoc((Artifact) a);
					}
				} else if (action instanceof CorrectRequirementsAction) {
					if (partName.equals("RequirementsDoc")) {
						((CorrectRequirementsAction) action)
								.addRequirementsDoc((Artifact) a);
					}
				} else if (action instanceof CreateDesignAction) {
					if (partName.equals("AssociatedRequirementsDoc")) {
						((CreateDesignAction) action)
								.addAssociatedRequirementsDoc((Artifact) a);
					}
				} else if (action instanceof ReviewDesignAction) {
					if (partName.equals("AssociatedRequirementsDoc")) {
						((ReviewDesignAction) action)
								.addAssociatedRequirementsDoc((Artifact) a);
					}
				} else if (action instanceof CorrectDesignAction) {
					if (partName.equals("AssociatedRequirementsDoc")) {
						((CorrectDesignAction) action)
								.addAssociatedRequirementsDoc((Artifact) a);
					}
				} else if (action instanceof CreateCodeAction) {
					if (partName.equals("AssociatedRequirementsDoc")) {
						((CreateCodeAction) action)
								.addAssociatedRequirementsDoc((Artifact) a);
					}
				} else if (action instanceof InspectCodeAction) {
					if (partName.equals("AssociatedRequirementsDoc")) {
						((InspectCodeAction) action)
								.addAssociatedRequirementsDoc((Artifact) a);
					}
				} else if (action instanceof CorrectCodeAction) {
					if (partName.equals("AssociatedRequirementsDoc")) {
						((CorrectCodeAction) action)
								.addAssociatedRequirementsDoc((Artifact) a);
					}
				} else if (action instanceof IntegrateCodeAction) {
					if (partName.equals("AssociatedRequirementsDoc")) {
						((IntegrateCodeAction) action)
								.addAssociatedRequirementsDoc((Artifact) a);
					}
				} else if (action instanceof SystemTestAction) {
				} else if (action instanceof CreateSystemTestPlanAction) {
					if (partName.equals("AssociatedRequirementsDoc")) {
						((CreateSystemTestPlanAction) action)
								.addAssociatedRequirementsDoc((Artifact) a);
					}
				} else if (action instanceof ReviewSystemTestPlanAction) {
					if (partName.equals("AssociatedRequirementsDoc")) {
						((ReviewSystemTestPlanAction) action)
								.addAssociatedRequirementsDoc((Artifact) a);
					}
				} else if (action instanceof CorrectSystemTestPlanAction) {
					if (partName.equals("AssociatedRequirementsDoc")) {
						((CorrectSystemTestPlanAction) action)
								.addAssociatedRequirementsDoc((Artifact) a);
					}
				} else if (action instanceof DeliverProductAction) {
				} else if (action instanceof ChangePayRateAction) {
				} else if (action instanceof GiveBonusAction) {
				} else if (action instanceof FireAction) {
				} else if (action instanceof PurchaseToolAction) {
				}
			}
		} else if (objTypeName.equals("DesignDocument")) {
			DesignDocument a = state.getArtifactStateRepository()
					.getDesignDocumentStateRepository().get(keyValStr);
			if (a != null) {
				if (action instanceof CreateRequirementsAction) {
					if (partName.equals("AssociatedDesignDoc")) {
						((CreateRequirementsAction) action)
								.addAssociatedDesignDoc((Artifact) a);
					}
				} else if (action instanceof ReviewRequirementsAction) {
				} else if (action instanceof CorrectRequirementsAction) {
				} else if (action instanceof CreateDesignAction) {
					if (partName.equals("DesignDoc")) {
						((CreateDesignAction) action)
								.addDesignDoc((Artifact) a);
					}
				} else if (action instanceof ReviewDesignAction) {
					if (partName.equals("DesignDoc")) {
						((ReviewDesignAction) action)
								.addDesignDoc((Artifact) a);
					}
				} else if (action instanceof CorrectDesignAction) {
					if (partName.equals("DesignDoc")) {
						((CorrectDesignAction) action)
								.addDesignDoc((Artifact) a);
					}
				} else if (action instanceof CreateCodeAction) {
					if (partName.equals("AssociatedDesignDocument")) {
						((CreateCodeAction) action)
								.addAssociatedDesignDocument((Artifact) a);
					}
				} else if (action instanceof InspectCodeAction) {
					if (partName.equals("AssociatedDesignDoc")) {
						((InspectCodeAction) action)
								.addAssociatedDesignDoc((Artifact) a);
					}
				} else if (action instanceof CorrectCodeAction) {
					if (partName.equals("AssociatedDesignDoc")) {
						((CorrectCodeAction) action)
								.addAssociatedDesignDoc((Artifact) a);
					}
				} else if (action instanceof IntegrateCodeAction) {
					if (partName.equals("AssociatedDesignDoc")) {
						((IntegrateCodeAction) action)
								.addAssociatedDesignDoc((Artifact) a);
					}
				} else if (action instanceof SystemTestAction) {
				} else if (action instanceof CreateSystemTestPlanAction) {
				} else if (action instanceof ReviewSystemTestPlanAction) {
				} else if (action instanceof CorrectSystemTestPlanAction) {
				} else if (action instanceof DeliverProductAction) {
				} else if (action instanceof ChangePayRateAction) {
				} else if (action instanceof GiveBonusAction) {
				} else if (action instanceof FireAction) {
				} else if (action instanceof PurchaseToolAction) {
				}
			}
		} else if (objTypeName.equals("Code")) {
			Code a = state.getArtifactStateRepository()
					.getCodeStateRepository().get(keyValStr);
			if (a != null) {
				if (action instanceof CreateRequirementsAction) {
					if (partName.equals("AssociatedCodeDoc")) {
						((CreateRequirementsAction) action)
								.addAssociatedCodeDoc((Artifact) a);
					}
				} else if (action instanceof ReviewRequirementsAction) {
				} else if (action instanceof CorrectRequirementsAction) {
				} else if (action instanceof CreateDesignAction) {
					if (partName.equals("AssociatedCodeDoc")) {
						((CreateDesignAction) action)
								.addAssociatedCodeDoc((Artifact) a);
					}
				} else if (action instanceof ReviewDesignAction) {
				} else if (action instanceof CorrectDesignAction) {
				} else if (action instanceof CreateCodeAction) {
					if (partName.equals("CodeDoc")) {
						((CreateCodeAction) action).addCodeDoc((Artifact) a);
					}
				} else if (action instanceof InspectCodeAction) {
					if (partName.equals("CodeDoc")) {
						((InspectCodeAction) action).addCodeDoc((Artifact) a);
					}
				} else if (action instanceof CorrectCodeAction) {
					if (partName.equals("CodeDoc")) {
						((CorrectCodeAction) action).addCodeDoc((Artifact) a);
					}
				} else if (action instanceof IntegrateCodeAction) {
					if (partName.equals("CodeDoc")) {
						((IntegrateCodeAction) action).addCodeDoc((Artifact) a);
					}
				} else if (action instanceof SystemTestAction) {
					if (partName.equals("CodeDoc")) {
						((SystemTestAction) action).addCodeDoc((Artifact) a);
					}
				} else if (action instanceof CreateSystemTestPlanAction) {
					if (partName.equals("AssociatedCodeDoc")) {
						((CreateSystemTestPlanAction) action)
								.addAssociatedCodeDoc((Artifact) a);
					}
				} else if (action instanceof ReviewSystemTestPlanAction) {
				} else if (action instanceof CorrectSystemTestPlanAction) {
				} else if (action instanceof DeliverProductAction) {
					if (partName.equals("CodeDoc")) {
						((DeliverProductAction) action)
								.addCodeDoc((Artifact) a);
					}
				} else if (action instanceof ChangePayRateAction) {
				} else if (action instanceof GiveBonusAction) {
				} else if (action instanceof FireAction) {
				} else if (action instanceof PurchaseToolAction) {
				}
			}
		} else if (objTypeName.equals("SystemTestPlan")) {
			SystemTestPlan a = state.getArtifactStateRepository()
					.getSystemTestPlanStateRepository().get(keyValStr);
			if (a != null) {
				if (action instanceof CreateRequirementsAction) {
					if (partName.equals("AssociatedSystemTestPlan")) {
						((CreateRequirementsAction) action)
								.addAssociatedSystemTestPlan((Artifact) a);
					}
				} else if (action instanceof ReviewRequirementsAction) {
				} else if (action instanceof CorrectRequirementsAction) {
				} else if (action instanceof CreateDesignAction) {
				} else if (action instanceof ReviewDesignAction) {
				} else if (action instanceof CorrectDesignAction) {
				} else if (action instanceof CreateCodeAction) {
					if (partName.equals("AssociatedSystemTestPlan")) {
						((CreateCodeAction) action)
								.addAssociatedSystemTestPlan((Artifact) a);
					}
				} else if (action instanceof InspectCodeAction) {
				} else if (action instanceof CorrectCodeAction) {
				} else if (action instanceof IntegrateCodeAction) {
				} else if (action instanceof SystemTestAction) {
					if (partName.equals("AssociatedSystemTestPlan")) {
						((SystemTestAction) action)
								.addAssociatedSystemTestPlan((Artifact) a);
					}
				} else if (action instanceof CreateSystemTestPlanAction) {
					if (partName.equals("SystemTestPlanDoc")) {
						((CreateSystemTestPlanAction) action)
								.addSystemTestPlanDoc((Artifact) a);
					}
				} else if (action instanceof ReviewSystemTestPlanAction) {
					if (partName.equals("TestPlan")) {
						((ReviewSystemTestPlanAction) action)
								.addTestPlan((Artifact) a);
					}
				} else if (action instanceof CorrectSystemTestPlanAction) {
					if (partName.equals("TestPlan")) {
						((CorrectSystemTestPlanAction) action)
								.addTestPlan((Artifact) a);
					}
				} else if (action instanceof DeliverProductAction) {
				} else if (action instanceof ChangePayRateAction) {
				} else if (action instanceof GiveBonusAction) {
				} else if (action instanceof FireAction) {
				} else if (action instanceof PurchaseToolAction) {
				}
			}
		} else if (objTypeName.equals("SEProject")) {
			SEProject a = state.getProjectStateRepository()
					.getSEProjectStateRepository().get(keyValStr);
			if (a != null) {
				if (action instanceof CreateRequirementsAction) {
					if (partName.equals("Proj")) {
						((CreateRequirementsAction) action)
								.addProj((Project) a);
					}
				} else if (action instanceof ReviewRequirementsAction) {
					if (partName.equals("Proj")) {
						((ReviewRequirementsAction) action)
								.addProj((Project) a);
					}
				} else if (action instanceof CorrectRequirementsAction) {
					if (partName.equals("Proj")) {
						((CorrectRequirementsAction) action)
								.addProj((Project) a);
					}
				} else if (action instanceof CreateDesignAction) {
					if (partName.equals("Proj")) {
						((CreateDesignAction) action).addProj((Project) a);
					}
				} else if (action instanceof ReviewDesignAction) {
					if (partName.equals("Proj")) {
						((ReviewDesignAction) action).addProj((Project) a);
					}
				} else if (action instanceof CorrectDesignAction) {
					if (partName.equals("Proj")) {
						((CorrectDesignAction) action).addProj((Project) a);
					}
				} else if (action instanceof CreateCodeAction) {
					if (partName.equals("Proj")) {
						((CreateCodeAction) action).addProj((Project) a);
					}
				} else if (action instanceof InspectCodeAction) {
					if (partName.equals("Proj")) {
						((InspectCodeAction) action).addProj((Project) a);
					}
				} else if (action instanceof CorrectCodeAction) {
					if (partName.equals("Proj")) {
						((CorrectCodeAction) action).addProj((Project) a);
					}
				} else if (action instanceof IntegrateCodeAction) {
					if (partName.equals("Proj")) {
						((IntegrateCodeAction) action).addProj((Project) a);
					}
				} else if (action instanceof SystemTestAction) {
					if (partName.equals("Proj")) {
						((SystemTestAction) action).addProj((Project) a);
					}
				} else if (action instanceof CreateSystemTestPlanAction) {
					if (partName.equals("Proj")) {
						((CreateSystemTestPlanAction) action)
								.addProj((Project) a);
					}
				} else if (action instanceof ReviewSystemTestPlanAction) {
					if (partName.equals("Proj")) {
						((ReviewSystemTestPlanAction) action)
								.addProj((Project) a);
					}
				} else if (action instanceof CorrectSystemTestPlanAction) {
					if (partName.equals("Proj")) {
						((CorrectSystemTestPlanAction) action)
								.addProj((Project) a);
					}
				} else if (action instanceof DeliverProductAction) {
					if (partName.equals("Proj")) {
						((DeliverProductAction) action).addProj((Project) a);
					}
				} else if (action instanceof ChangePayRateAction) {
				} else if (action instanceof GiveBonusAction) {
					if (partName.equals("ProjectWithBudget")) {
						((GiveBonusAction) action)
								.addProjectWithBudget((Project) a);
					}
				} else if (action instanceof FireAction) {
				} else if (action instanceof PurchaseToolAction) {
					if (partName.equals("Proj")) {
						((PurchaseToolAction) action).addProj((Project) a);
					}
				}
			}
		} else if (objTypeName.equals("RequirementsCaptureTool")) {
			RequirementsCaptureTool a = state.getToolStateRepository()
					.getRequirementsCaptureToolStateRepository().get(keyValStr);
			if (a != null) {
				if (action instanceof CreateRequirementsAction) {
					if (partName.equals("RequirementsCaptureTool")) {
						((CreateRequirementsAction) action)
								.addRequirementsCaptureTool((Tool) a);
					}
				} else if (action instanceof ReviewRequirementsAction) {
				} else if (action instanceof CorrectRequirementsAction) {
					if (partName.equals("RequirementsCaptureTool")) {
						((CorrectRequirementsAction) action)
								.addRequirementsCaptureTool((Tool) a);
					}
				} else if (action instanceof CreateDesignAction) {
				} else if (action instanceof ReviewDesignAction) {
				} else if (action instanceof CorrectDesignAction) {
				} else if (action instanceof CreateCodeAction) {
				} else if (action instanceof InspectCodeAction) {
				} else if (action instanceof CorrectCodeAction) {
				} else if (action instanceof IntegrateCodeAction) {
				} else if (action instanceof SystemTestAction) {
				} else if (action instanceof CreateSystemTestPlanAction) {
				} else if (action instanceof ReviewSystemTestPlanAction) {
				} else if (action instanceof CorrectSystemTestPlanAction) {
				} else if (action instanceof DeliverProductAction) {
				} else if (action instanceof ChangePayRateAction) {
				} else if (action instanceof GiveBonusAction) {
				} else if (action instanceof FireAction) {
				} else if (action instanceof PurchaseToolAction) {
					if (partName.equals("SETool")) {
						((PurchaseToolAction) action).addSETool((Tool) a);
					}
				}
			}
		} else if (objTypeName.equals("DesignEnvironment")) {
			DesignEnvironment a = state.getToolStateRepository()
					.getDesignEnvironmentStateRepository().get(keyValStr);
			if (a != null) {
				if (action instanceof CreateRequirementsAction) {
				} else if (action instanceof ReviewRequirementsAction) {
				} else if (action instanceof CorrectRequirementsAction) {
				} else if (action instanceof CreateDesignAction) {
					if (partName.equals("DesignEnvironment")) {
						((CreateDesignAction) action)
								.addDesignEnvironment((Tool) a);
					}
				} else if (action instanceof ReviewDesignAction) {
				} else if (action instanceof CorrectDesignAction) {
					if (partName.equals("DesignEnvironment")) {
						((CorrectDesignAction) action)
								.addDesignEnvironment((Tool) a);
					}
				} else if (action instanceof CreateCodeAction) {
				} else if (action instanceof InspectCodeAction) {
				} else if (action instanceof CorrectCodeAction) {
				} else if (action instanceof IntegrateCodeAction) {
				} else if (action instanceof SystemTestAction) {
				} else if (action instanceof CreateSystemTestPlanAction) {
				} else if (action instanceof ReviewSystemTestPlanAction) {
				} else if (action instanceof CorrectSystemTestPlanAction) {
				} else if (action instanceof DeliverProductAction) {
				} else if (action instanceof ChangePayRateAction) {
				} else if (action instanceof GiveBonusAction) {
				} else if (action instanceof FireAction) {
				} else if (action instanceof PurchaseToolAction) {
					if (partName.equals("SETool")) {
						((PurchaseToolAction) action).addSETool((Tool) a);
					}
				}
			}
		} else if (objTypeName.equals("IDE")) {
			IDE a = state.getToolStateRepository().getIDEStateRepository()
					.get(keyValStr);
			if (a != null) {
				if (action instanceof CreateRequirementsAction) {
				} else if (action instanceof ReviewRequirementsAction) {
				} else if (action instanceof CorrectRequirementsAction) {
				} else if (action instanceof CreateDesignAction) {
				} else if (action instanceof ReviewDesignAction) {
				} else if (action instanceof CorrectDesignAction) {
				} else if (action instanceof CreateCodeAction) {
					if (partName.equals("DevelopmentEnvironment")) {
						((CreateCodeAction) action)
								.addDevelopmentEnvironment((Tool) a);
					}
				} else if (action instanceof InspectCodeAction) {
				} else if (action instanceof CorrectCodeAction) {
					if (partName.equals("DevelopmentEnvironment")) {
						((CorrectCodeAction) action)
								.addDevelopmentEnvironment((Tool) a);
					}
				} else if (action instanceof IntegrateCodeAction) {
					if (partName.equals("DevelopmentEnvironment")) {
						((IntegrateCodeAction) action)
								.addDevelopmentEnvironment((Tool) a);
					}
				} else if (action instanceof SystemTestAction) {
				} else if (action instanceof CreateSystemTestPlanAction) {
				} else if (action instanceof ReviewSystemTestPlanAction) {
				} else if (action instanceof CorrectSystemTestPlanAction) {
				} else if (action instanceof DeliverProductAction) {
				} else if (action instanceof ChangePayRateAction) {
				} else if (action instanceof GiveBonusAction) {
				} else if (action instanceof FireAction) {
				} else if (action instanceof PurchaseToolAction) {
					if (partName.equals("SETool")) {
						((PurchaseToolAction) action).addSETool((Tool) a);
					}
				}
			}
		} else if (objTypeName.equals("AutomatedTestingTool")) {
			AutomatedTestingTool a = state.getToolStateRepository()
					.getAutomatedTestingToolStateRepository().get(keyValStr);
			if (a != null) {
				if (action instanceof CreateRequirementsAction) {
				} else if (action instanceof ReviewRequirementsAction) {
				} else if (action instanceof CorrectRequirementsAction) {
				} else if (action instanceof CreateDesignAction) {
				} else if (action instanceof ReviewDesignAction) {
				} else if (action instanceof CorrectDesignAction) {
				} else if (action instanceof CreateCodeAction) {
				} else if (action instanceof InspectCodeAction) {
				} else if (action instanceof CorrectCodeAction) {
				} else if (action instanceof IntegrateCodeAction) {
				} else if (action instanceof SystemTestAction) {
					if (partName.equals("TestingTool")) {
						((SystemTestAction) action).addTestingTool((Tool) a);
					}
				} else if (action instanceof CreateSystemTestPlanAction) {
					if (partName.equals("TestingTool")) {
						((CreateSystemTestPlanAction) action)
								.addTestingTool((Tool) a);
					}
				} else if (action instanceof ReviewSystemTestPlanAction) {
				} else if (action instanceof CorrectSystemTestPlanAction) {
					if (partName.equals("TestingTool")) {
						((CorrectSystemTestPlanAction) action)
								.addTestingTool((Tool) a);
					}
				} else if (action instanceof DeliverProductAction) {
				} else if (action instanceof ChangePayRateAction) {
				} else if (action instanceof GiveBonusAction) {
				} else if (action instanceof FireAction) {
				} else if (action instanceof PurchaseToolAction) {
					if (partName.equals("SETool")) {
						((PurchaseToolAction) action).addSETool((Tool) a);
					}
				}
			}
		} else if (objTypeName.equals("ACustomer")) {
			ACustomer a = state.getCustomerStateRepository()
					.getACustomerStateRepository().get(keyValStr);
			if (a != null) {
				if (action instanceof CreateRequirementsAction) {
				} else if (action instanceof ReviewRequirementsAction) {
				} else if (action instanceof CorrectRequirementsAction) {
				} else if (action instanceof CreateDesignAction) {
				} else if (action instanceof ReviewDesignAction) {
				} else if (action instanceof CorrectDesignAction) {
				} else if (action instanceof CreateCodeAction) {
				} else if (action instanceof InspectCodeAction) {
				} else if (action instanceof CorrectCodeAction) {
				} else if (action instanceof IntegrateCodeAction) {
				} else if (action instanceof SystemTestAction) {
				} else if (action instanceof CreateSystemTestPlanAction) {
				} else if (action instanceof ReviewSystemTestPlanAction) {
				} else if (action instanceof CorrectSystemTestPlanAction) {
				} else if (action instanceof DeliverProductAction) {
					if (partName.equals("Cust")) {
						((DeliverProductAction) action).addCust((Customer) a);
					}
				} else if (action instanceof ChangePayRateAction) {
				} else if (action instanceof GiveBonusAction) {
				} else if (action instanceof FireAction) {
				} else if (action instanceof PurchaseToolAction) {
				}
			}
		}
	}

	private void setMinAndMax() {
		if (action instanceof CreateRequirementsAction) {
			if (partName.equals("Emp")) {
				minNumParts = 1;
				maxNumParts = 999999;
			} else if (partName.equals("ReqDoc")) {
				minNumParts = 1;
				maxNumParts = 1;
			} else if (partName.equals("Proj")) {
				minNumParts = 1;
				maxNumParts = 1;
			} else if (partName.equals("RequirementsCaptureTool")) {
				minNumParts = 0;
				maxNumParts = 999999;
			} else if (partName.equals("AssociatedCodeDoc")) {
				minNumParts = 1;
				maxNumParts = 1;
			} else if (partName.equals("AssociatedDesignDoc")) {
				minNumParts = 1;
				maxNumParts = 1;
			} else if (partName.equals("AssociatedSystemTestPlan")) {
				minNumParts = 1;
				maxNumParts = 1;
			}
		} else if (action instanceof ReviewRequirementsAction) {
			if (partName.equals("Emp")) {
				minNumParts = 1;
				maxNumParts = 999999;
			} else if (partName.equals("RequirementsDoc")) {
				minNumParts = 1;
				maxNumParts = 1;
			} else if (partName.equals("Proj")) {
				minNumParts = 1;
				maxNumParts = 1;
			}
		} else if (action instanceof CorrectRequirementsAction) {
			if (partName.equals("Emp")) {
				minNumParts = 1;
				maxNumParts = 999999;
			} else if (partName.equals("RequirementsDoc")) {
				minNumParts = 1;
				maxNumParts = 1;
			} else if (partName.equals("Proj")) {
				minNumParts = 1;
				maxNumParts = 1;
			} else if (partName.equals("RequirementsCaptureTool")) {
				minNumParts = 0;
				maxNumParts = 999999;
			}
		} else if (action instanceof CreateDesignAction) {
			if (partName.equals("Emp")) {
				minNumParts = 1;
				maxNumParts = 999999;
			} else if (partName.equals("DesignDoc")) {
				minNumParts = 1;
				maxNumParts = 1;
			} else if (partName.equals("Proj")) {
				minNumParts = 1;
				maxNumParts = 1;
			} else if (partName.equals("AssociatedRequirementsDoc")) {
				minNumParts = 1;
				maxNumParts = 1;
			} else if (partName.equals("DesignEnvironment")) {
				minNumParts = 0;
				maxNumParts = 999999;
			} else if (partName.equals("AssociatedCodeDoc")) {
				minNumParts = 1;
				maxNumParts = 1;
			}
		} else if (action instanceof ReviewDesignAction) {
			if (partName.equals("Emp")) {
				minNumParts = 1;
				maxNumParts = 999999;
			} else if (partName.equals("DesignDoc")) {
				minNumParts = 1;
				maxNumParts = 1;
			} else if (partName.equals("Proj")) {
				minNumParts = 1;
				maxNumParts = 1;
			} else if (partName.equals("AssociatedRequirementsDoc")) {
				minNumParts = 1;
				maxNumParts = 1;
			}
		} else if (action instanceof CorrectDesignAction) {
			if (partName.equals("Emp")) {
				minNumParts = 1;
				maxNumParts = 999999;
			} else if (partName.equals("DesignDoc")) {
				minNumParts = 1;
				maxNumParts = 1;
			} else if (partName.equals("Proj")) {
				minNumParts = 1;
				maxNumParts = 1;
			} else if (partName.equals("AssociatedRequirementsDoc")) {
				minNumParts = 1;
				maxNumParts = 1;
			} else if (partName.equals("DesignEnvironment")) {
				minNumParts = 0;
				maxNumParts = 999999;
			}
		} else if (action instanceof CreateCodeAction) {
			if (partName.equals("Emp")) {
				minNumParts = 1;
				maxNumParts = 999999;
			} else if (partName.equals("CodeDoc")) {
				minNumParts = 1;
				maxNumParts = 1;
			} else if (partName.equals("Proj")) {
				minNumParts = 1;
				maxNumParts = 1;
			} else if (partName.equals("AssociatedRequirementsDoc")) {
				minNumParts = 1;
				maxNumParts = 1;
			} else if (partName.equals("AssociatedDesignDocument")) {
				minNumParts = 1;
				maxNumParts = 1;
			} else if (partName.equals("DevelopmentEnvironment")) {
				minNumParts = 0;
				maxNumParts = 999999;
			} else if (partName.equals("AssociatedSystemTestPlan")) {
				minNumParts = 1;
				maxNumParts = 1;
			}
		} else if (action instanceof InspectCodeAction) {
			if (partName.equals("Emp")) {
				minNumParts = 3;
				maxNumParts = 999999;
			} else if (partName.equals("CodeDoc")) {
				minNumParts = 1;
				maxNumParts = 1;
			} else if (partName.equals("Proj")) {
				minNumParts = 1;
				maxNumParts = 1;
			} else if (partName.equals("AssociatedRequirementsDoc")) {
				minNumParts = 1;
				maxNumParts = 1;
			} else if (partName.equals("AssociatedDesignDoc")) {
				minNumParts = 1;
				maxNumParts = 1;
			}
		} else if (action instanceof CorrectCodeAction) {
			if (partName.equals("Emp")) {
				minNumParts = 1;
				maxNumParts = 999999;
			} else if (partName.equals("CodeDoc")) {
				minNumParts = 1;
				maxNumParts = 1;
			} else if (partName.equals("Proj")) {
				minNumParts = 1;
				maxNumParts = 1;
			} else if (partName.equals("AssociatedRequirementsDoc")) {
				minNumParts = 1;
				maxNumParts = 1;
			} else if (partName.equals("AssociatedDesignDoc")) {
				minNumParts = 1;
				maxNumParts = 1;
			} else if (partName.equals("DevelopmentEnvironment")) {
				minNumParts = 0;
				maxNumParts = 999999;
			}
		} else if (action instanceof IntegrateCodeAction) {
			if (partName.equals("Emp")) {
				minNumParts = 1;
				maxNumParts = 999999;
			} else if (partName.equals("CodeDoc")) {
				minNumParts = 1;
				maxNumParts = 1;
			} else if (partName.equals("Proj")) {
				minNumParts = 1;
				maxNumParts = 1;
			} else if (partName.equals("AssociatedRequirementsDoc")) {
				minNumParts = 1;
				maxNumParts = 1;
			} else if (partName.equals("AssociatedDesignDoc")) {
				minNumParts = 1;
				maxNumParts = 1;
			} else if (partName.equals("DevelopmentEnvironment")) {
				minNumParts = 0;
				maxNumParts = 999999;
			}
		} else if (action instanceof SystemTestAction) {
			if (partName.equals("CodeDoc")) {
				minNumParts = 1;
				maxNumParts = 1;
			} else if (partName.equals("Proj")) {
				minNumParts = 1;
				maxNumParts = 1;
			} else if (partName.equals("Emp")) {
				minNumParts = 1;
				maxNumParts = 999999;
			} else if (partName.equals("AssociatedSystemTestPlan")) {
				minNumParts = 1;
				maxNumParts = 1;
			} else if (partName.equals("TestingTool")) {
				minNumParts = 0;
				maxNumParts = 999999;
			}
		} else if (action instanceof CreateSystemTestPlanAction) {
			if (partName.equals("Emp")) {
				minNumParts = 1;
				maxNumParts = 999999;
			} else if (partName.equals("AssociatedCodeDoc")) {
				minNumParts = 1;
				maxNumParts = 1;
			} else if (partName.equals("Proj")) {
				minNumParts = 1;
				maxNumParts = 1;
			} else if (partName.equals("SystemTestPlanDoc")) {
				minNumParts = 1;
				maxNumParts = 1;
			} else if (partName.equals("AssociatedRequirementsDoc")) {
				minNumParts = 1;
				maxNumParts = 1;
			} else if (partName.equals("TestingTool")) {
				minNumParts = 0;
				maxNumParts = 999999;
			}
		} else if (action instanceof ReviewSystemTestPlanAction) {
			if (partName.equals("Emp")) {
				minNumParts = 1;
				maxNumParts = 999999;
			} else if (partName.equals("TestPlan")) {
				minNumParts = 1;
				maxNumParts = 1;
			} else if (partName.equals("AssociatedRequirementsDoc")) {
				minNumParts = 1;
				maxNumParts = 1;
			} else if (partName.equals("Proj")) {
				minNumParts = 1;
				maxNumParts = 1;
			}
		} else if (action instanceof CorrectSystemTestPlanAction) {
			if (partName.equals("Emp")) {
				minNumParts = 1;
				maxNumParts = 999999;
			} else if (partName.equals("TestPlan")) {
				minNumParts = 1;
				maxNumParts = 1;
			} else if (partName.equals("AssociatedRequirementsDoc")) {
				minNumParts = 1;
				maxNumParts = 1;
			} else if (partName.equals("Proj")) {
				minNumParts = 1;
				maxNumParts = 1;
			} else if (partName.equals("TestingTool")) {
				minNumParts = 0;
				maxNumParts = 999999;
			}
		} else if (action instanceof DeliverProductAction) {
			if (partName.equals("Emp")) {
				minNumParts = 1;
				maxNumParts = 1;
			} else if (partName.equals("Proj")) {
				minNumParts = 1;
				maxNumParts = 1;
			} else if (partName.equals("CodeDoc")) {
				minNumParts = 1;
				maxNumParts = 1;
			} else if (partName.equals("Cust")) {
				minNumParts = 1;
				maxNumParts = 1;
			}
		} else if (action instanceof BreakAction) {
			if (partName.equals("Breaker")) {
				minNumParts = 1;
				maxNumParts = 1;
			}
		} else if (action instanceof GetSickAction) {
			if (partName.equals("SickPerson")) {
				minNumParts = 1;
				maxNumParts = 1;
			}
		} else if (action instanceof QuitAction) {
			if (partName.equals("Quitter")) {
				minNumParts = 1;
				maxNumParts = 1;
			}
		} else if (action instanceof IntroduceNewRequirementsAction) {
			if (partName.equals("Cust")) {
				minNumParts = 1;
				maxNumParts = 1;
			} else if (partName.equals("AssociatedRequirementsDocument")) {
				minNumParts = 1;
				maxNumParts = 1;
			} else if (partName.equals("Proj")) {
				minNumParts = 1;
				maxNumParts = 1;
			} else if (partName.equals("EmpWOverheadText")) {
				minNumParts = 1;
				maxNumParts = 999999;
			} else if (partName.equals("AssociatedCode")) {
				minNumParts = 1;
				maxNumParts = 1;
			} else if (partName.equals("AssociatedDesignDocument")) {
				minNumParts = 1;
				maxNumParts = 1;
			} else if (partName.equals("AssociatedSystemTestPlan")) {
				minNumParts = 1;
				maxNumParts = 1;
			}
		} else if (action instanceof UpdateProjectAttributesAction) {
			if (partName.equals("Proj")) {
				minNumParts = 1;
				maxNumParts = 1;
			} else if (partName.equals("Emp")) {
				minNumParts = 1;
				maxNumParts = 999999;
			}
		} else if (action instanceof ChangePayRateAction) {
			if (partName.equals("Emp")) {
				minNumParts = 1;
				maxNumParts = 1;
			}
		} else if (action instanceof GiveBonusAction) {
			if (partName.equals("Emp")) {
				minNumParts = 1;
				maxNumParts = 1;
			} else if (partName.equals("ProjectWithBudget")) {
				minNumParts = 1;
				maxNumParts = 1;
			}
		} else if (action instanceof FireAction) {
			if (partName.equals("FiredPerson")) {
				minNumParts = 1;
				maxNumParts = 1;
			}
		} else if (action instanceof PurchaseToolAction) {
			if (partName.equals("EmpWhoseMenuClickedOn")) {
				minNumParts = 1;
				maxNumParts = 1;
			} else if (partName.equals("SETool")) {
				minNumParts = 1;
				maxNumParts = 999999;
			} else if (partName.equals("Proj")) {
				minNumParts = 1;
				maxNumParts = 1;
			}
		} else if (action instanceof SuggestedRequirementsPhaseDurationAction) {
			if (partName.equals("Proj")) {
				minNumParts = 1;
				maxNumParts = 1;
			} else if (partName.equals("Emp")) {
				minNumParts = 1;
				maxNumParts = 999999;
			}
		} else if (action instanceof SuggestedDesignPhaseDurationAction) {
			if (partName.equals("Proj")) {
				minNumParts = 1;
				maxNumParts = 1;
			} else if (partName.equals("Emp")) {
				minNumParts = 1;
				maxNumParts = 999999;
			}
		} else if (action instanceof SuggestedImplIntegrationPhaseDurationAction) {
			if (partName.equals("Proj")) {
				minNumParts = 1;
				maxNumParts = 1;
			} else if (partName.equals("Emp")) {
				minNumParts = 1;
				maxNumParts = 999999;
			}
		} else if (action instanceof SuggestedTestingPhaseDurationAction) {
			if (partName.equals("Proj")) {
				minNumParts = 1;
				maxNumParts = 1;
			} else if (partName.equals("Emp")) {
				minNumParts = 1;
				maxNumParts = 999999;
			}
		}
	}

	public boolean actionCancelled() {
		return actionCancelled;
	}

	public class ExitListener extends WindowAdapter {
		public void windowClosing(WindowEvent event) {
			actionCancelled = true;
		}
	}
}
