/* File generated by: simse.codegenerator.guigenerator.DisplayedEmployeeGenerator */
package simse.gui;

import simse.adts.objects.*;

import java.awt.event.*;
import java.awt.Image;
import javax.swing.JMenuItem;

public class DisplayedEmployee {
	private Employee userObject;
	private String userIconLocation;
	private Image userIcon;
	private boolean userDisplayed; // is this employee displayed on screen
	private boolean activated; // if this employee is a start state object, this
								// is automatically true; if created by a rule,
								// false

	// grid locations of the SimSEObject
	// <xLocation, yLocation> where <0, 0> is the top left tile
	private int xLocation;
	private int yLocation;

	private JMenuItem userMenu;

	public DisplayedEmployee(Employee emp, String il, ActionListener a,
			boolean d, boolean ra, int x, int y) {
		userObject = emp;
		userIconLocation = il;
		if (userIconLocation != null) {
			userIcon = ImageLoader.getImageFromURL(il);
		}
		activated = ra;
		setDisplayed(d);
		setXYLocations(x, y);
	}

	public Image getUserIcon() {
		return userIcon;
	}

	public void setUserIcon(String imageLocation) {
		userIconLocation = imageLocation;
		userIcon = ImageLoader.getImageFromURL(userIconLocation);
	}

	public int getXLocation() {
		return xLocation;
	}

	public int getYLocation() {
		return yLocation;
	}

	public boolean isActivated() {
		return activated;
	}

	public boolean isDisplayed() {
		return userDisplayed;
	}

	public void setActivated(boolean a) {
		activated = a;
	}

	public void setDisplayed(boolean b) {
		userDisplayed = b;
	}

	public void setXYLocations(int x, int y) {
		xLocation = x;
		yLocation = y;
	}

	public boolean checkXYLocations(int x, int y) {
		return xLocation == x && yLocation == y;
	}

	// returns the Employee object associated with this DisplayedEmployee
	public Employee getEmployee() {
		return userObject;
	}
}